
GET http://localhost:3000/users
Content-Type: application/json

   {    
        "firstname": "Shela",
        "lastname": "Skooooo",
        "email": "st@gmail.com",
        "password": "password"
        
        }